#!/usr/bin/env python3
"""
Filing Clerk — moves document-of-record attachments from Gmail into Google Drive.

Why this exists
---------------
The Cowork scheduled task of the same name could never do this. It reached Drive
through an MCP connector whose create_file takes content only as an inline string,
so every byte of every PDF had to be generated by a language model one token at a
time. A 90 KB statement is ~120,000 base64 characters; it does not fit in a single
tool call, so nothing was ever filed unattended. See size_note in filing-rules.json.

Here the bytes go Gmail API -> this process -> Drive API as a resumable upload.
No model is in the path and there is no practical size limit.

The rule table stays where it already lives: filing-rules.json in Drive, so Andrew
adds a sender without touching this code. Exceptions go to Todoist, never email.
"""

from __future__ import annotations

import base64
import io
import json
import os
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone

import requests
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaIoBaseUpload

SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/drive",
]

# The finance root is pinned by id, never resolved by title.
#
# On 2026-09-07 the folder was renamed "3. Financial Insurance" -> "03. Financial
# Insurance". The title lookup that stood here found nothing, and within seven
# seconds a new, empty "3. Financial Insurance" existed at My Drive root with
# documents filed into it. A title is a label Andrew is free to change; the id is
# the folder's identity. So there is deliberately no fallback below: if the id
# does not resolve the run aborts. It must never search by title and must never
# create a folder - filing into a plausible-looking wrong place is worse than not
# running at all.
FINANCE_ROOT_ID = "12EAKPnQEl4KiPED6RjUwT_znkd-VXjPL"
CLERK_FOLDER_NAME = "_Filing Clerk"
RULES_NAME = "filing-rules.json"
FILED_NAME = "filed.jsonl"

TODOIST_API = "https://api.todoist.com/api/v1/tasks"
TODOIST_LABEL = "agent"

DRY_RUN = os.environ.get("DRY_RUN", "").lower() in ("1", "true", "yes")
LOOKBACK_DAYS = int(os.environ.get("LOOKBACK_DAYS", "30"))
MAX_EXCEPTIONS = int(os.environ.get("MAX_EXCEPTIONS", "5"))
MAX_FILES_PER_RUN = int(os.environ.get("MAX_FILES_PER_RUN", "40"))
# The workflow allows 20 minutes. Stop the rule loop before the runner kills it,
# so the run ends on our terms with the ledger flushed and a line in the log
# naming the rule it stopped at, instead of vanishing mid-upload.
RUN_BUDGET_SECONDS = int(os.environ.get("RUN_BUDGET_SECONDS", "900"))


def log(msg: str) -> None:
    print(f"[{datetime.now(timezone.utc).isoformat(timespec='seconds')}] {msg}", flush=True)


# --------------------------------------------------------------------------- auth


def credentials() -> Credentials:
    missing = [
        k
        for k in ("GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN")
        if not os.environ.get(k)
    ]
    if missing:
        sys.exit(f"Missing secrets: {', '.join(missing)}. See README.")
    creds = Credentials(
        token=None,
        refresh_token=os.environ["GOOGLE_REFRESH_TOKEN"],
        client_id=os.environ["GOOGLE_CLIENT_ID"],
        client_secret=os.environ["GOOGLE_CLIENT_SECRET"],
        token_uri="https://oauth2.googleapis.com/token",
        scopes=SCOPES,
    )
    creds.refresh(Request())
    return creds


# --------------------------------------------------------------------- drive paths


class Drive:
    """Thin Drive wrapper with a path cache, so repeated lookups cost nothing."""

    def __init__(self, service):
        self.svc = service
        self._folder_cache: dict[tuple[str, str], str] = {}
        self._root_id: str | None = None
        self._root_title: str | None = None

    def _find_child(self, parent_id: str, name: str, folder_only: bool = True) -> str | None:
        key = (parent_id, name)
        if folder_only and key in self._folder_cache:
            return self._folder_cache[key]
        safe = name.replace("'", "\\'")
        q = f"'{parent_id}' in parents and name = '{safe}' and trashed = false"
        if folder_only:
            q += " and mimeType = 'application/vnd.google-apps.folder'"
        res = self.svc.files().list(q=q, fields="files(id,name)", pageSize=10).execute()
        files = res.get("files", [])
        if not files:
            return None
        if folder_only:
            self._folder_cache[key] = files[0]["id"]
        return files[0]["id"]

    def finance_root(self) -> str:
        """Resolve the finance root by id, or abort. Never by title, never created."""
        if self._root_id:
            return self._root_id

        abort_tail = (
            "Nothing was filed. Fix FINANCE_ROOT_ID in filing_clerk.py, or restore the "
            "folder in Drive, then run again. This run will not fall back to a title "
            "lookup and will not create a folder."
        )
        try:
            meta = (
                self.svc.files()
                .get(fileId=FINANCE_ROOT_ID, fields="id,name,mimeType,trashed")
                .execute()
            )
        except HttpError as exc:
            sys.exit(
                f"ABORTING: cannot resolve the finance root folder id "
                f"{FINANCE_ROOT_ID} in Drive ({exc}). {abort_tail}"
            )
        if meta.get("mimeType") != "application/vnd.google-apps.folder":
            sys.exit(
                f"ABORTING: {FINANCE_ROOT_ID} is not a folder "
                f"(mimeType {meta.get('mimeType')!r}). {abort_tail}"
            )
        if meta.get("trashed"):
            sys.exit(
                f"ABORTING: the finance root folder {FINANCE_ROOT_ID} "
                f"({meta.get('name')!r}) is in the Drive trash. {abort_tail}"
            )

        self._root_id = meta["id"]
        self._root_title = meta.get("name") or FINANCE_ROOT_ID
        log(f"Finance root: {self._root_title!r} ({self._root_id})")
        return self._root_id

    def root_label(self) -> str:
        """The root's live Drive title, for log lines and Todoist exceptions.

        Resolves the root if that has not happened yet, so a message can never
        quote a title the code merely assumed.
        """
        self.finance_root()
        return self._root_title or FINANCE_ROOT_ID

    def resolve_path(self, relative_path: str) -> str | None:
        """Walk 'A/B/C' under the finance root. Returns None if any segment is missing.

        Deliberately does NOT create folders. filing-rules.json says never guess a
        destination; a missing folder is a question for Andrew, not a decision here.
        """
        node = self.finance_root()
        for segment in [s for s in relative_path.split("/") if s]:
            child = self._find_child(node, segment)
            if child is None:
                return None
            node = child
        return node

    def find_file(self, parent_id: str, name: str) -> str | None:
        return self._find_child(parent_id, name, folder_only=False)

    def find_config(self, parent_id: str, name: str) -> str:
        """Find exactly one config file, or abort.

        Drive allows several files with the same name in one folder. On 2026-09-07
        two filing-rules.json existed at once - one with corrected folder paths, one
        with the new invoice rules - and this code silently took whichever Drive
        returned first, so half the config was ignored with nothing in the log to
        show it. Loading the wrong rule table is worse than not running: it files
        real documents to stale destinations. So refuse to guess.
        """
        safe = name.replace("'", "\\'")
        res = (
            self.svc.files()
            .list(
                q=f"'{parent_id}' in parents and name = '{safe}' and trashed = false",
                fields="files(id,name,modifiedTime)",
                pageSize=10,
            )
            .execute()
        )
        files = res.get("files", [])
        if not files:
            sys.exit(f"Cannot find {name} in the _Filing Clerk folder.")
        if len(files) > 1:
            listing = "\n".join(
                f"  {f['id']}  modified {f.get('modifiedTime')}" for f in files
            )
            sys.exit(
                f"ABORTING: {len(files)} files named {name} in the _Filing Clerk folder.\n"
                f"{listing}\n"
                "Exactly one must exist. Trash the stale copies in Drive, keeping the one "
                "that is actually current, then run again. Nothing was filed."
            )
        return files[0]["id"]

    def read_text(self, file_id: str) -> str:
        return self.svc.files().get_media(fileId=file_id).execute().decode("utf-8")

    def name_exists(self, parent_id: str, name: str) -> bool:
        return self.find_file(parent_id, name) is not None

    def existing_numbers(self, parent_id: str) -> set[str]:
        """Trailing statement numbers of the PDFs already in a folder.

        "... Statement 52.pdf" -> "52". Used to dedupe on statement number so a
        re-emailed statement under a new date does not land as a second copy.
        """
        numbers: set[str] = set()
        page = None
        while True:
            resp = (
                self.svc.files()
                .list(
                    q=f"'{parent_id}' in parents and trashed=false "
                    "and mimeType='application/pdf'",
                    fields="nextPageToken, files(name)",
                    pageToken=page,
                    pageSize=1000,
                )
                .execute()
            )
            for item in resp.get("files", []):
                m = re.search(r"(\d+)(?=\.[A-Za-z0-9]+$)", item["name"])
                if m:
                    numbers.add(m.group(1))
            page = resp.get("nextPageToken")
            if not page:
                break
        return numbers

    def upload(self, parent_id: str, name: str, data: bytes, mime: str) -> str:
        media = MediaIoBaseUpload(io.BytesIO(data), mimetype=mime, resumable=True)
        meta = {"name": name, "parents": [parent_id]}
        created = self.svc.files().create(body=meta, media_body=media, fields="id").execute()
        return created["id"]

    def replace_text(self, file_id: str, text: str, mime: str = "application/json") -> None:
        media = MediaIoBaseUpload(io.BytesIO(text.encode("utf-8")), mimetype=mime, resumable=True)
        self.svc.files().update(fileId=file_id, media_body=media).execute()

    def create_text(self, parent_id: str, name: str, text: str, mime: str) -> str:
        media = MediaIoBaseUpload(io.BytesIO(text.encode("utf-8")), mimetype=mime, resumable=True)
        meta = {"name": name, "parents": [parent_id]}
        return self.svc.files().create(body=meta, media_body=media, fields="id").execute()["id"]


# ----------------------------------------------------------------------- rendering


MONTHS = {
    m.lower(): i
    for i, m in enumerate(
        [
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December",
        ],
        start=1,
    )
}


def date_from_subject(subject: str) -> str | None:
    """Pull a date out of a subject line. Returns YYYY-MM-DD or None.

    Handles the shapes that actually turn up in this mailbox, e.g.
    'Home loan | Quarterly statement 31/08/2026' and '... 31 August 2026'.
    """
    m = re.search(r"(\d{4})[-/](\d{1,2})[-/](\d{1,2})", subject)
    if m:
        y, mo, d = m.groups()
        return f"{int(y):04d}-{int(mo):02d}-{int(d):02d}"
    m = re.search(r"(\d{1,2})[-/](\d{1,2})[-/](\d{4})", subject)
    if m:
        d, mo, y = m.groups()  # SA convention: day first
        return f"{int(y):04d}-{int(mo):02d}-{int(d):02d}"
    m = re.search(r"(\d{1,2})\s+([A-Za-z]{3,9})\s+(\d{4})", subject)
    if m:
        d, name, y = m.groups()
        for full, num in MONTHS.items():
            if full.startswith(name.lower()[:3]):
                return f"{int(y):04d}-{num:02d}-{int(d):02d}"
    return None


def slugify(text: str, limit: int = 60) -> str:
    text = re.sub(r"[\\/:*?\"<>|]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:limit].strip()


PROVIDERS = {
    "ampath": "Ampath",
    "lancet": "Lancet",
    "pathcare": "PathCare",
    "histologic": "Histologic",
}


def provider_from_sender(sender: str) -> str:
    """Name the lab from the sender address, for {provider} in a filename.

    Without this a pathology account files as '2026-08-17 Pathology Account.pdf'
    and you cannot tell Ampath from Lancet without opening it.
    """
    low = sender.lower()
    for key, label in PROVIDERS.items():
        if key in low:
            return label
    return ""


def attachment_label(filename: str) -> str:
    """A human label distinguishing sibling attachments in one email."""
    low = filename.lower()
    for key, label in (
        ("receipt", "Receipt"),
        ("invoice", "Invoice"),
        ("statement", "Statement"),
        ("summary", "Summary"),
        # MTN names its two PDFs BA<acct>_<timestamp>_INV.pdf and ..._STMT.pdf, so
        # without these the pair would file as "(1)" and "(2)" and nothing on disk
        # would say which was the tax invoice.
        ("_inv", "Tax Invoice"),
        ("_stmt", "Statement"),
    ):
        if key in low:
            return label
    return ""


def disambiguate(names: dict[str, str]) -> dict[str, str]:
    """Make every target name in one message unique.

    Several senders attach more than one PDF to a single email - Anthropic sends an
    invoice and a receipt, Ninety One sends one statement per fund - and the rule's
    name template often renders them identically. Left alone the first would upload
    and the second would hit the 'already in Drive' check and be recorded as filed
    without ever being written. That is silent data loss, so it must not be possible.

    Keyed by source attachment filename, so the result is stable across runs and does
    not depend on the order Gmail happens to return parts in.
    """
    groups: dict[str, list[str]] = {}
    for source, target in names.items():
        groups.setdefault(target, []).append(source)

    out: dict[str, str] = {}
    for target, sources in groups.items():
        if len(sources) == 1:
            out[sources[0]] = target
            continue
        sources = sorted(sources)
        labels = [attachment_label(s) for s in sources]
        use_labels = all(labels) and len(set(labels)) == len(labels)
        stem, _, ext = target.rpartition(".")
        for i, source in enumerate(sources, start=1):
            suffix = f" - {labels[i - 1]}" if use_labels else f" ({i})"
            out[source] = f"{stem}{suffix}.{ext}"
    return out


def render_name(
    template: str, *, msg_date: str, subject: str, attachment_name: str, sender: str = ""
) -> str:
    date = date_from_subject(subject) or msg_date
    trailing = re.search(r"(\d+)(?=\.[A-Za-z0-9]+$)", attachment_name)

    # {ref} is a document reference like Anthropic's 2982-5722-1886. Dates have the
    # same hyphenated-digits shape, so a subject carrying one produced names like
    # "2026-04-13 Lancet Pathology Account 2026-04-13.pdf". Reject any candidate
    # that is a date, or that is simply the date we already resolved.
    ref_value = ""
    for cand in re.findall(r"#?([A-Z0-9]{3,}-[A-Z0-9-]+)", subject):
        if cand == date or re.fullmatch(r"\d{2,4}[-/]\d{1,2}[-/]\d{1,4}", cand):
            continue
        ref_value = cand
        break
    values = {
        "{date}": date,
        "{yyyy-mm}": date[:7],
        "{subject}": slugify(subject),
        "{n}": trailing.group(1) if trailing else "1",
        "{ref}": ref_value,
        "{provider}": provider_from_sender(sender),
    }
    out = template
    for token, value in values.items():
        out = out.replace(token, value)
    out = re.sub(r"\s{2,}", " ", out).replace(" .pdf", ".pdf").strip()
    return out


# --------------------------------------------------------------------------- rules


@dataclass
class Rule:
    id: str
    dest: str
    name: str
    senders: list[str] = field(default_factory=list)
    subject_any: list[str] = field(default_factory=list)
    mailbox: str = "gmail"
    # Only file attachments whose filename contains one of these (case-insensitive).
    # Lets several rules share one sender+subject but split by account, keying on the
    # attachment filename prefix (e.g. "GOLD BUSINESS ACCOUNT" vs "PREMIER CHEQUE").
    attachment_any: list[str] = field(default_factory=list)
    # "number" -> skip an attachment whose trailing statement number ({n}) already
    # exists in dest, regardless of the date prefix. Stops the same statement being
    # filed twice when it is re-emailed on a later date.
    dedupe_on: str = ""

    @classmethod
    def parse(cls, raw: dict) -> "Rule":
        senders = raw.get("from_any") or ([raw["from"]] if raw.get("from") else [])
        return cls(
            id=raw.get("id", "unnamed"),
            dest=raw["dest"],
            name=raw["name"],
            senders=[s.lower() for s in senders],
            subject_any=raw.get("subject_any", []),
            mailbox=raw.get("mailbox", "gmail"),
            attachment_any=raw.get("attachment_any", []),
            dedupe_on=raw.get("dedupe_on", ""),
        )

    def gmail_query(self, after: str) -> str:
        senders = " OR ".join(f"from:{s}" for s in self.senders)
        q = f"({senders}) has:attachment after:{after}"
        if self.subject_any:
            subjects = " OR ".join(f'subject:"{s}"' for s in self.subject_any)
            q += f" ({subjects})"
        return q


# -------------------------------------------------------------------------- todoist


def raise_todoist(title: str, body: str, key: str, priority: int = 4) -> bool:
    token = os.environ.get("TODOIST_TOKEN")
    if not token:
        log(f"NO TODOIST_TOKEN — would have raised: {title}")
        return False
    if DRY_RUN:
        log(f"DRY RUN — would raise Todoist item: {title}")
        return False
    resp = requests.post(
        TODOIST_API,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json={
            "content": title,
            "description": f"{body}\n\nkey: {key}",
            "labels": [TODOIST_LABEL],
            "priority": priority,  # Todoist REST: 4 = p1 ... 1 = p4
        },
        timeout=30,
    )
    if resp.status_code >= 300:
        log(f"Todoist rejected the item ({resp.status_code}): {resp.text[:200]}")
        return False
    return True


# -------------------------------------------------------------------------- ledger


class Ledger:
    """filed.jsonl, flushed as the run goes rather than once at the end.

    Until 2026-09-09 every record was held in memory and written in a single call
    after the last rule. The nightly runs of 8 and 9 September uploaded five FNB
    statements to Drive and wrote none of them down, because whatever ended those
    runs ended them before that one write. A stale ledger is not cosmetic: the
    Gmail Steward archives a document only once filed.jsonl confirms it was filed,
    so the statements stayed in the inbox and steward/unfiled/noreply@fnb.co.za
    stayed open for five consecutive Steward runs. Flushing after every rule caps
    the loss at the rule in flight.
    """

    def __init__(self, drive: "Drive", folder_id: str) -> None:
        self.drive = drive
        self.folder_id = folder_id
        self.file_id = drive.find_file(folder_id, FILED_NAME)
        self.lines = drive.read_text(self.file_id).splitlines() if self.file_id else []
        self.pending: list[dict] = []
        self.written = 0
        self.degraded = False
        self.keys: set[str] = set()
        for line in self.lines:
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            if rec.get("dedupe_key"):
                self.keys.add(rec["dedupe_key"])
            elif rec.get("message_id") and rec.get("filename"):
                self.keys.add(f"{rec['message_id']}::{rec['filename']}")

    def add(self, record: dict) -> None:
        self.pending.append(record)
        if record.get("dedupe_key"):
            self.keys.add(record["dedupe_key"])

    def flush(self) -> None:
        if not self.pending or DRY_RUN:
            return
        payload = "\n".join(self.lines + [json.dumps(r) for r in self.pending]) + "\n"
        try:
            if self.file_id:
                self.drive.replace_text(self.file_id, payload, mime="application/json")
            else:
                self.file_id = self.drive.create_text(
                    self.folder_id, FILED_NAME, payload, "application/json"
                )
            self.lines = payload.splitlines()
            self.written += len(self.pending)
            log(f"{FILED_NAME} +{len(self.pending)} records ({len(self.lines)} total)")
            self.pending = []
            self.degraded = False
        except Exception as exc:  # noqa: BLE001 - the run must not die on a log write
            # Keep the records and try again on the next flush. Nothing is dropped
            # until rescue() runs, and rescue() only ever creates a new file.
            self.degraded = True
            log(f"{FILED_NAME} write failed, holding {len(self.pending)} record(s): {exc}")

    def rescue(self) -> str | None:
        """Last resort: park unflushed records in a new file. Returns its name."""
        if not self.pending or DRY_RUN:
            return None
        name = f"filed-recovery-{datetime.now(timezone.utc):%Y-%m-%dT%H%M%SZ}.jsonl"
        body = "\n".join(json.dumps(r) for r in self.pending) + "\n"
        try:
            self.drive.create_text(self.folder_id, name, body, "application/json")
            log(f"Parked {len(self.pending)} unwritten record(s) in {name}")
            return name
        except Exception as exc:  # noqa: BLE001
            log(f"Could not park unwritten records: {exc}")
            return None


# ----------------------------------------------------------------------------- run


def main() -> int:
    creds = credentials()
    gmail = build("gmail", "v1", credentials=creds, cache_discovery=False)
    drive = Drive(build("drive", "v3", credentials=creds, cache_discovery=False))

    clerk_folder = drive.resolve_path(CLERK_FOLDER_NAME)
    if not clerk_folder:
        sys.exit(f"Cannot find '{drive.root_label()}/{CLERK_FOLDER_NAME}' in Drive.")

    rules_id = drive.find_config(clerk_folder, RULES_NAME)
    config = json.loads(drive.read_text(rules_id))
    log(f"Loaded {RULES_NAME} v{config.get('version')} — {len(config['rules'])} rules")

    never_file = [s.lower() for s in config.get("never_file", [])]

    ledger = Ledger(drive, clerk_folder)
    already = ledger.keys
    log(f"{FILED_NAME}: {len(ledger.lines)} records, {len(already)} dedupe keys")

    after = (datetime.now(timezone.utc) - timedelta(days=LOOKBACK_DAYS)).strftime("%Y/%m/%d")
    started = datetime.now(timezone.utc)
    exceptions: list[tuple[str, str, str]] = []
    skipped_outlook: list[str] = []
    filed_count = 0

    for raw_rule in config["rules"]:
        rule = Rule.parse(raw_rule)

        if rule.mailbox == "outlook":
            # Cannot be reached from here and that is expected, not a fault.
            # Outlook filing stays a live-session job on Andrew's Mac.
            skipped_outlook.append(rule.id)
            continue
        if filed_count >= MAX_FILES_PER_RUN:
            log("Hit MAX_FILES_PER_RUN; the rest waits for the next run.")
            break
        elapsed = (datetime.now(timezone.utc) - started).total_seconds()
        if elapsed > RUN_BUDGET_SECONDS:
            log(
                f"Run budget reached ({elapsed:.0f}s) at rule '{rule.id}'; "
                "stopping cleanly. The remaining rules wait for the next run."
            )
            break

        try:
            listing = (
                gmail.users()
                .messages()
                .list(userId="me", q=rule.gmail_query(after), maxResults=50)
                .execute()
            )
        except HttpError as exc:
            log(f"[{rule.id}] Gmail search failed: {exc}")
            continue

        messages = listing.get("messages", [])
        if not messages:
            continue
        log(f"[{rule.id}] {len(messages)} candidate message(s)")

        dest_id = drive.resolve_path(rule.dest)
        if dest_id is None:
            exceptions.append(
                (
                    f"Filing Clerk: destination folder missing for {rule.id}",
                    f"filing-rules.json rule '{rule.id}' points at "
                    f"'{drive.root_label()}/{rule.dest}', which does not exist in Drive. "
                    "Create the folder, or change the dest in filing-rules.json. "
                    "Nothing was filed for this rule.",
                    f"filing-clerk/missing-folder/{rule.id}",
                )
            )
            log(f"[{rule.id}] destination missing: {rule.dest}")
            continue

        dest_numbers = drive.existing_numbers(dest_id) if rule.dedupe_on == "number" else set()

        for ref in messages:
            if filed_count >= MAX_FILES_PER_RUN:
                break
            msg = (
                gmail.users()
                .messages()
                .get(userId="me", id=ref["id"], format="full")
                .execute()
            )
            headers = {h["name"].lower(): h["value"] for h in msg["payload"].get("headers", [])}
            sender = headers.get("from", "").lower()
            subject = headers.get("subject", "")

            if any(nf and nf in sender for nf in never_file):
                continue

            msg_date = datetime.fromtimestamp(
                int(msg["internalDate"]) / 1000, tz=timezone.utc
            ).strftime("%Y-%m-%d")

            # Collect every PDF in the message FIRST, so sibling attachments that
            # render to the same name can be told apart before anything uploads.
            attachments: list[tuple[str, str]] = []
            for part in walk_parts(msg["payload"]):
                filename = part.get("filename") or ""
                attachment_id = part.get("body", {}).get("attachmentId")
                if not filename or not attachment_id:
                    continue
                if not filename.lower().endswith(".pdf"):
                    continue
                if rule.attachment_any and not any(
                    pat.lower() in filename.lower() for pat in rule.attachment_any
                ):
                    # This attachment belongs to a different account rule sharing the
                    # same sender+subject. Leave it for that rule.
                    continue
                attachments.append((filename, attachment_id))

            proposed = {
                filename: render_name(
                    rule.name,
                    msg_date=msg_date,
                    subject=subject,
                    attachment_name=filename,
                    sender=sender,
                )
                for filename, _ in attachments
            }
            resolved = disambiguate(proposed)

            for filename, attachment_id in attachments:
                dedupe_key = f"{ref['id']}::{filename}"
                if dedupe_key in already:
                    continue

                target_name = resolved[filename]

                if rule.dedupe_on == "number":
                    m = re.search(r"(\d+)(?=\.[A-Za-z0-9]+$)", filename)
                    if m and m.group(1) in dest_numbers:
                        # A statement with this number is already filed (perhaps under
                        # a different date prefix). Record it and do not file a second.
                        already.add(dedupe_key)
                        ledger.add(
                            {
                                "ts": datetime.now(timezone.utc).isoformat(),
                                "rule": rule.id,
                                "message_id": ref["id"],
                                "filename": filename,
                                "dedupe_key": dedupe_key,
                                "drive_name": target_name,
                                "dest": rule.dest,
                                "outcome": "already_present_number",
                                "source": "github-actions",
                            }
                        )
                        log(f"[{rule.id}] statement #{m.group(1)} already filed, skipping {filename}")
                        continue

                if drive.name_exists(dest_id, target_name):
                    # Already there from an interactive session — record it so we
                    # stop reconsidering it, but do not upload a second copy.
                    already.add(dedupe_key)
                    ledger.add(
                        {
                            "ts": datetime.now(timezone.utc).isoformat(),
                            "rule": rule.id,
                            "message_id": ref["id"],
                            "filename": filename,
                            "dedupe_key": dedupe_key,
                            "drive_name": target_name,
                            "dest": rule.dest,
                            "outcome": "already_present",
                            "source": "github-actions",
                        }
                    )
                    log(f"[{rule.id}] already in Drive: {target_name}")
                    continue

                attachment = (
                    gmail.users()
                    .messages()
                    .attachments()
                    .get(userId="me", messageId=ref["id"], id=attachment_id)
                    .execute()
                )
                data = base64.urlsafe_b64decode(attachment["data"])

                if DRY_RUN:
                    log(f"[{rule.id}] DRY RUN would file {len(data)}B -> {rule.dest}/{target_name}")
                    continue

                # Password-protected PDFs (payslips, bank statements, Momentum) are
                # filed exactly as issued. Nothing here opens or inspects them.
                file_id = drive.upload(dest_id, target_name, data, "application/pdf")
                filed_count += 1
                already.add(dedupe_key)
                ledger.add(
                    {
                        "ts": datetime.now(timezone.utc).isoformat(),
                        "rule": rule.id,
                        "message_id": ref["id"],
                        "filename": filename,
                        "dedupe_key": dedupe_key,
                        "drive_id": file_id,
                        "drive_name": target_name,
                        "dest": rule.dest,
                        "bytes": len(data),
                        "outcome": "filed",
                        "source": "github-actions",
                    }
                )
                log(f"[{rule.id}] filed {len(data)}B -> {rule.dest}/{target_name}")

        # Write the ledger down before moving to the next rule. Everything filed
        # up to here survives whatever happens after here.
        ledger.flush()

    ledger.flush()
    parked = ledger.rescue() if ledger.pending else None
    if parked:
        exceptions.append(
            (
                "Filing Clerk: could not write filed.jsonl",
                f"{len(ledger.pending)} record(s) for documents that WERE filed to Drive "
                f"could not be written to {FILED_NAME}; they are parked in '{parked}' in "
                "the _Filing Clerk folder. Until they are merged back, the Gmail Steward "
                "will not archive that mail and will keep reporting it unfiled. Append the "
                "parked lines to filed.jsonl, then delete the recovery file.",
                f"filing-clerk/ledger-write-failed/{parked}",
            )
        )

    for title, body, key in exceptions[:MAX_EXCEPTIONS]:
        raise_todoist(title, body, key, priority=2)

    if skipped_outlook:
        log(f"Skipped {len(skipped_outlook)} outlook-only rule(s) by design: {', '.join(skipped_outlook)}")
    log(
        f"Done. Filed {filed_count}, records written {ledger.written}, "
        f"exceptions {len(exceptions)}, "
        f"elapsed {(datetime.now(timezone.utc) - started).total_seconds():.0f}s."
    )
    return 1 if parked else 0


def walk_parts(payload: dict):
    yield payload
    for part in payload.get("parts", []) or []:
        yield from walk_parts(part)


if __name__ == "__main__":
    raise SystemExit(main())
