#!/usr/bin/env python3
"""
Filing Clerk — moves document-of-record attachments from Gmail into Google Drive.

Why this exists
---------------
The Cowork scheduled task of the same name could never do this. It reached Drive
through an MCP connector whose create_file takes content only as an inline string,
so every byte of every PDF had to be generated by a language model one token at a
time. A 90 KB statement is ~120,000 base64 characters; it does not fit in a single
tool call, so nothing was ever filed unattended. See size_note in filing-rules.json.

Here the bytes go Gmail API -> this process -> Drive API as a resumable upload.
No model is in the path and there is no practical size limit.

The rule table stays where it already lives: filing-rules.json in Drive, so Andrew
adds a sender without touching this code. Exceptions go to Todoist, never email.
"""

from __future__ import annotations

import base64
import io
import json
import os
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone

import requests
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaIoBaseUpload

SCOPES = [
    "https://www.googleapis.com/auth/gmail.readonly",
    "https://www.googleapis.com/auth/drive",
]

FINANCE_ROOT_NAME = "3. Financial Insurance"
CLERK_FOLDER_NAME = "_Filing Clerk"
RULES_NAME = "filing-rules.json"
FILED_NAME = "filed.jsonl"

TODOIST_API = "https://api.todoist.com/api/v1/tasks"
TODOIST_LABEL = "agent"

DRY_RUN = os.environ.get("DRY_RUN", "").lower() in ("1", "true", "yes")
LOOKBACK_DAYS = int(os.environ.get("LOOKBACK_DAYS", "30"))
MAX_EXCEPTIONS = int(os.environ.get("MAX_EXCEPTIONS", "5"))
MAX_FILES_PER_RUN = int(os.environ.get("MAX_FILES_PER_RUN", "40"))


def log(msg: str) -> None:
    print(f"[{datetime.now(timezone.utc).isoformat(timespec='seconds')}] {msg}", flush=True)


# --------------------------------------------------------------------------- auth


def credentials() -> Credentials:
    missing = [
        k
        for k in ("GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN")
        if not os.environ.get(k)
    ]
    if missing:
        sys.exit(f"Missing secrets: {', '.join(missing)}. See README.")
    creds = Credentials(
        token=None,
        refresh_token=os.environ["GOOGLE_REFRESH_TOKEN"],
        client_id=os.environ["GOOGLE_CLIENT_ID"],
        client_secret=os.environ["GOOGLE_CLIENT_SECRET"],
        token_uri="https://oauth2.googleapis.com/token",
        scopes=SCOPES,
    )
    creds.refresh(Request())
    return creds


# --------------------------------------------------------------------- drive paths


class Drive:
    """Thin Drive wrapper with a path cache, so repeated lookups cost nothing."""

    def __init__(self, service):
        self.svc = service
        self._folder_cache: dict[tuple[str, str], str] = {}
        self._root_id: str | None = None

    def _find_child(self, parent_id: str, name: str, folder_only: bool = True) -> str | None:
        key = (parent_id, name)
        if folder_only and key in self._folder_cache:
            return self._folder_cache[key]
        safe = name.replace("'", "\\'")
        q = f"'{parent_id}' in parents and name = '{safe}' and trashed = false"
        if folder_only:
            q += " and mimeType = 'application/vnd.google-apps.folder'"
        res = self.svc.files().list(q=q, fields="files(id,name)", pageSize=10).execute()
        files = res.get("files", [])
        if not files:
            return None
        if folder_only:
            self._folder_cache[key] = files[0]["id"]
        return files[0]["id"]

    def finance_root(self) -> str:
        if self._root_id:
            return self._root_id
        res = (
            self.svc.files()
            .list(
                q=(
                    f"name = '{FINANCE_ROOT_NAME}' and trashed = false "
                    "and mimeType = 'application/vnd.google-apps.folder'"
                ),
                fields="files(id,name)",
                pageSize=5,
            )
            .execute()
        )
        files = res.get("files", [])
        if not files:
            sys.exit(f"Cannot find the '{FINANCE_ROOT_NAME}' folder in Drive.")
        self._root_id = files[0]["id"]
        return self._root_id

    def resolve_path(self, relative_path: str) -> str | None:
        """Walk 'A/B/C' under the finance root. Returns None if any segment is missing.

        Deliberately does NOT create folders. filing-rules.json says never guess a
        destination; a missing folder is a question for Andrew, not a decision here.
        """
        node = self.finance_root()
        for segment in [s for s in relative_path.split("/") if s]:
            child = self._find_child(node, segment)
            if child is None:
                return None
            node = child
        return node

    def find_file(self, parent_id: str, name: str) -> str | None:
        return self._find_child(parent_id, name, folder_only=False)

    def find_config(self, parent_id: str, name: str) -> str:
        """Find exactly one config file, or abort.

        Drive allows several files with the same name in one folder. On 2026-09-07
        two filing-rules.json existed at once - one with corrected folder paths, one
        with the new invoice rules - and this code silently took whichever Drive
        returned first, so half the config was ignored with nothing in the log to
        show it. Loading the wrong rule table is worse than not running: it files
        real documents to stale destinations. So refuse to guess.
        """
        safe = name.replace("'", "\\'")
        res = (
            self.svc.files()
            .list(
                q=f"'{parent_id}' in parents and name = '{safe}' and trashed = false",
                fields="files(id,name,modifiedTime)",
                pageSize=10,
            )
            .execute()
        )
        files = res.get("files", [])
        if not files:
            sys.exit(f"Cannot find {name} in the _Filing Clerk folder.")
        if len(files) > 1:
            listing = "\n".join(
                f"  {f['id']}  modified {f.get('modifiedTime')}" for f in files
            )
            sys.exit(
                f"ABORTING: {len(files)} files named {name} in the _Filing Clerk folder.\n"
                f"{listing}\n"
                "Exactly one must exist. Trash the stale copies in Drive, keeping the one "
                "that is actually current, then run again. Nothing was filed."
            )
        return files[0]["id"]

    def read_text(self, file_id: str) -> str:
        return self.svc.files().get_media(fileId=file_id).execute().decode("utf-8")

    def name_exists(self, parent_id: str, name: str) -> bool:
        return self.find_file(parent_id, name) is not None

    def upload(self, parent_id: str, name: str, data: bytes, mime: str) -> str:
        media = MediaIoBaseUpload(io.BytesIO(data), mimetype=mime, resumable=True)
        meta = {"name": name, "parents": [parent_id]}
        created = self.svc.files().create(body=meta, media_body=media, fields="id").execute()
        return created["id"]

    def replace_text(self, file_id: str, text: str, mime: str = "application/json") -> None:
        media = MediaIoBaseUpload(io.BytesIO(text.encode("utf-8")), mimetype=mime, resumable=True)
        self.svc.files().update(fileId=file_id, media_body=media).execute()

    def create_text(self, parent_id: str, name: str, text: str, mime: str) -> str:
        media = MediaIoBaseUpload(io.BytesIO(text.encode("utf-8")), mimetype=mime, resumable=True)
        meta = {"name": name, "parents": [parent_id]}
        return self.svc.files().create(body=meta, media_body=media, fields="id").execute()["id"]


# ----------------------------------------------------------------------- rendering


MONTHS = {
    m.lower(): i
    for i, m in enumerate(
        [
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December",
        ],
        start=1,
    )
}


def date_from_subject(subject: str) -> str | None:
    """Pull a date out of a subject line. Returns YYYY-MM-DD or None.

    Handles the shapes that actually turn up in this mailbox, e.g.
    'Home loan | Quarterly statement 31/08/2026' and '... 31 August 2026'.
    """
    m = re.search(r"(\d{4})[-/](\d{1,2})[-/](\d{1,2})", subject)
    if m:
        y, mo, d = m.groups()
        return f"{int(y):04d}-{int(mo):02d}-{int(d):02d}"
    m = re.search(r"(\d{1,2})[-/](\d{1,2})[-/](\d{4})", subject)
    if m:
        d, mo, y = m.groups()  # SA convention: day first
        return f"{int(y):04d}-{int(mo):02d}-{int(d):02d}"
    m = re.search(r"(\d{1,2})\s+([A-Za-z]{3,9})\s+(\d{4})", subject)
    if m:
        d, name, y = m.groups()
        for full, num in MONTHS.items():
            if full.startswith(name.lower()[:3]):
                return f"{int(y):04d}-{num:02d}-{int(d):02d}"
    return None


def slugify(text: str, limit: int = 60) -> str:
    text = re.sub(r"[\\/:*?\"<>|]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:limit].strip()


PROVIDERS = {
    "ampath": "Ampath",
    "lancet": "Lancet",
    "pathcare": "PathCare",
    "histologic": "Histologic",
}


def provider_from_sender(sender: str) -> str:
    """Name the lab from the sender address, for {provider} in a filename.

    Without this a pathology account files as '2026-08-17 Pathology Account.pdf'
    and you cannot tell Ampath from Lancet without opening it.
    """
    low = sender.lower()
    for key, label in PROVIDERS.items():
        if key in low:
            return label
    return ""


def render_name(
    template: str, *, msg_date: str, subject: str, attachment_name: str, sender: str = ""
) -> str:
    date = date_from_subject(subject) or msg_date
    trailing = re.search(r"(\d+)(?=\.[A-Za-z0-9]+$)", attachment_name)
    ref = re.search(r"#?([A-Z0-9]{3,}-[A-Z0-9-]+)", subject)
    values = {
        "{date}": date,
        "{yyyy-mm}": date[:7],
        "{subject}": slugify(subject),
        "{n}": trailing.group(1) if trailing else "1",
        "{ref}": ref.group(1) if ref else "",
        "{provider}": provider_from_sender(sender),
    }
    out = template
    for token, value in values.items():
        out = out.replace(token, value)
    out = re.sub(r"\s{2,}", " ", out).replace(" .pdf", ".pdf").strip()
    return out


# --------------------------------------------------------------------------- rules


@dataclass
class Rule:
    id: str
    dest: str
    name: str
    senders: list[str] = field(default_factory=list)
    subject_any: list[str] = field(default_factory=list)
    mailbox: str = "gmail"

    @classmethod
    def parse(cls, raw: dict) -> "Rule":
        senders = raw.get("from_any") or ([raw["from"]] if raw.get("from") else [])
        return cls(
            id=raw.get("id", "unnamed"),
            dest=raw["dest"],
            name=raw["name"],
            senders=[s.lower() for s in senders],
            subject_any=raw.get("subject_any", []),
            mailbox=raw.get("mailbox", "gmail"),
        )

    def gmail_query(self, after: str) -> str:
        senders = " OR ".join(f"from:{s}" for s in self.senders)
        q = f"({senders}) has:attachment after:{after}"
        if self.subject_any:
            subjects = " OR ".join(f'subject:"{s}"' for s in self.subject_any)
            q += f" ({subjects})"
        return q


# -------------------------------------------------------------------------- todoist


def raise_todoist(title: str, body: str, key: str, priority: int = 4) -> bool:
    token = os.environ.get("TODOIST_TOKEN")
    if not token:
        log(f"NO TODOIST_TOKEN — would have raised: {title}")
        return False
    if DRY_RUN:
        log(f"DRY RUN — would raise Todoist item: {title}")
        return False
    resp = requests.post(
        TODOIST_API,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        json={
            "content": title,
            "description": f"{body}\n\nkey: {key}",
            "labels": [TODOIST_LABEL],
            "priority": priority,  # Todoist REST: 4 = p1 ... 1 = p4
        },
        timeout=30,
    )
    if resp.status_code >= 300:
        log(f"Todoist rejected the item ({resp.status_code}): {resp.text[:200]}")
        return False
    return True


# ----------------------------------------------------------------------------- run


def main() -> int:
    creds = credentials()
    gmail = build("gmail", "v1", credentials=creds, cache_discovery=False)
    drive = Drive(build("drive", "v3", credentials=creds, cache_discovery=False))

    clerk_folder = drive.resolve_path(CLERK_FOLDER_NAME)
    if not clerk_folder:
        sys.exit(f"Cannot find '{FINANCE_ROOT_NAME}/{CLERK_FOLDER_NAME}' in Drive.")

    rules_id = drive.find_config(clerk_folder, RULES_NAME)
    config = json.loads(drive.read_text(rules_id))
    log(f"Loaded {RULES_NAME} v{config.get('version')} — {len(config['rules'])} rules")

    never_file = [s.lower() for s in config.get("never_file", [])]

    filed_id = drive.find_file(clerk_folder, FILED_NAME)
    filed_lines = drive.read_text(filed_id).splitlines() if filed_id else []
    already: set[str] = set()
    for line in filed_lines:
        try:
            rec = json.loads(line)
        except json.JSONDecodeError:
            continue
        if rec.get("dedupe_key"):
            already.add(rec["dedupe_key"])
        elif rec.get("message_id") and rec.get("filename"):
            already.add(f"{rec['message_id']}::{rec['filename']}")
    log(f"{FILED_NAME}: {len(filed_lines)} records, {len(already)} dedupe keys")

    after = (datetime.now(timezone.utc) - timedelta(days=LOOKBACK_DAYS)).strftime("%Y/%m/%d")
    new_records: list[dict] = []
    exceptions: list[tuple[str, str, str]] = []
    skipped_outlook: list[str] = []
    filed_count = 0

    for raw_rule in config["rules"]:
        rule = Rule.parse(raw_rule)

        if rule.mailbox == "outlook":
            # Cannot be reached from here and that is expected, not a fault.
            # Outlook filing stays a live-session job on Andrew's Mac.
            skipped_outlook.append(rule.id)
            continue
        if filed_count >= MAX_FILES_PER_RUN:
            log("Hit MAX_FILES_PER_RUN; the rest waits for the next run.")
            break

        try:
            listing = (
                gmail.users()
                .messages()
                .list(userId="me", q=rule.gmail_query(after), maxResults=50)
                .execute()
            )
        except HttpError as exc:
            log(f"[{rule.id}] Gmail search failed: {exc}")
            continue

        messages = listing.get("messages", [])
        if not messages:
            continue
        log(f"[{rule.id}] {len(messages)} candidate message(s)")

        dest_id = drive.resolve_path(rule.dest)
        if dest_id is None:
            exceptions.append(
                (
                    f"Filing Clerk: destination folder missing for {rule.id}",
                    f"filing-rules.json rule '{rule.id}' points at "
                    f"'{FINANCE_ROOT_NAME}/{rule.dest}', which does not exist in Drive. "
                    "Create the folder, or change the dest in filing-rules.json. "
                    "Nothing was filed for this rule.",
                    f"filing-clerk/missing-folder/{rule.id}",
                )
            )
            log(f"[{rule.id}] destination missing: {rule.dest}")
            continue

        for ref in messages:
            if filed_count >= MAX_FILES_PER_RUN:
                break
            msg = (
                gmail.users()
                .messages()
                .get(userId="me", id=ref["id"], format="full")
                .execute()
            )
            headers = {h["name"].lower(): h["value"] for h in msg["payload"].get("headers", [])}
            sender = headers.get("from", "").lower()
            subject = headers.get("subject", "")

            if any(nf and nf in sender for nf in never_file):
                continue

            msg_date = datetime.fromtimestamp(
                int(msg["internalDate"]) / 1000, tz=timezone.utc
            ).strftime("%Y-%m-%d")

            for part in walk_parts(msg["payload"]):
                filename = part.get("filename") or ""
                body = part.get("body", {})
                attachment_id = body.get("attachmentId")
                if not filename or not attachment_id:
                    continue
                if not filename.lower().endswith(".pdf"):
                    continue

                dedupe_key = f"{ref['id']}::{filename}"
                if dedupe_key in already:
                    continue

                target_name = render_name(
                    rule.name,
                    msg_date=msg_date,
                    subject=subject,
                    attachment_name=filename,
                    sender=sender,
                )
                if drive.name_exists(dest_id, target_name):
                    # Already there from an interactive session — record it so we
                    # stop reconsidering it, but do not upload a second copy.
                    already.add(dedupe_key)
                    new_records.append(
                        {
                            "ts": datetime.now(timezone.utc).isoformat(),
                            "rule": rule.id,
                            "message_id": ref["id"],
                            "filename": filename,
                            "dedupe_key": dedupe_key,
                            "drive_name": target_name,
                            "dest": rule.dest,
                            "outcome": "already_present",
                            "source": "github-actions",
                        }
                    )
                    log(f"[{rule.id}] already in Drive: {target_name}")
                    continue

                attachment = (
                    gmail.users()
                    .messages()
                    .attachments()
                    .get(userId="me", messageId=ref["id"], id=attachment_id)
                    .execute()
                )
                data = base64.urlsafe_b64decode(attachment["data"])

                if DRY_RUN:
                    log(f"[{rule.id}] DRY RUN would file {len(data)}B -> {rule.dest}/{target_name}")
                    continue

                # Password-protected PDFs (payslips, bank statements, Momentum) are
                # filed exactly as issued. Nothing here opens or inspects them.
                file_id = drive.upload(dest_id, target_name, data, "application/pdf")
                filed_count += 1
                already.add(dedupe_key)
                new_records.append(
                    {
                        "ts": datetime.now(timezone.utc).isoformat(),
                        "rule": rule.id,
                        "message_id": ref["id"],
                        "filename": filename,
                        "dedupe_key": dedupe_key,
                        "drive_id": file_id,
                        "drive_name": target_name,
                        "dest": rule.dest,
                        "bytes": len(data),
                        "outcome": "filed",
                        "source": "github-actions",
                    }
                )
                log(f"[{rule.id}] filed {len(data)}B -> {rule.dest}/{target_name}")

    if new_records and not DRY_RUN:
        payload = "\n".join(filed_lines + [json.dumps(r) for r in new_records]) + "\n"
        if filed_id:
            drive.replace_text(filed_id, payload, mime="application/json")
        else:
            drive.create_text(clerk_folder, FILED_NAME, payload, "application/json")
        log(f"{FILED_NAME} updated (+{len(new_records)} records)")

    for title, body, key in exceptions[:MAX_EXCEPTIONS]:
        raise_todoist(title, body, key, priority=2)

    if skipped_outlook:
        log(f"Skipped {len(skipped_outlook)} outlook-only rule(s) by design: {', '.join(skipped_outlook)}")
    log(f"Done. Filed {filed_count}, records {len(new_records)}, exceptions {len(exceptions)}.")
    return 0


def walk_parts(payload: dict):
    yield payload
    for part in payload.get("parts", []) or []:
        yield from walk_parts(part)


if __name__ == "__main__":
    raise SystemExit(main())
